### PR TITLE
Revert "fix fly upwards" workaround

### LINKED ISSUE #9: Hangglider no longer slows fall
Seems to be caused by the fly-up fix (fd357093e511e3ee82855b586650110048f74876)

### PR DESCRIPTION
**Pull request by Niklp09**
- Closes https://github.com/mt-mods/hangglider/issues/9
- Make bedsheet.ogg sound mono (triggers a warning in 5.8 clients)
- Don't store `step_v` outside of on_step

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -158,6 +154,7 @@ minetest.register_entity("hangglider:glider", {
 	static_save = false,
 	textures = {"wool_white.png", "default_wood.png"},
 	on_step = function(self, dtime)
+		local step_v
```
Comment (OgelGames) [inline init.lua]: I think this could be moved down to where its value is set, on line 169.
